### ISSUE TITLE
checklist hébergeur: add checks CREATE SCHEMA and CREATE TABLE

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/le-phare.github.io#130]
@caillaudv a perdu 0,5j car il manquait les droits de création de schema et de tables dans la bdd.

Nous proposons d'ajouter les checks:
* CREATE SCHEMA
* CREATE TABLE dans le schema public.

Après le check effectué, ce qui est créé est drop par le script

**Comment by pierreboissinot** [comment]
> Ça rejoint #108 non ?

Je ne sais pas, je n'ai fait que reporté un problème soulevé par @caillaudv , je le laisse répondre

**Comment by thislg** [comment]
Ok, alors ça devrait être solutionné par l'ajout du rôle manquant tel qu'expliqué dans l'autre issue.
