### ISSUE TITLE
requirements: default PostgreSQL collation to fr_FR, setup servers' locale to fr_FR.UTF-8

### ISSUE THREAD

**Issue by lucasmirloup** [le-phare/le-phare.github.io#131]
## Problem
We discovered that several of our servers' PostgreSQL sort values in a case-sensitive manner, like this :
- MNO@example.com
- abc@example.com
- zyx@example.com

when we would like them to sort these values case-insensitively, like this :
- abc@example.com
- MNO@example.com
- zyx@example.com

## Explanation

These servers' locale have not been configured, and are using a default locale (`C` for example). 

At the creation of a PostgreSQL database, if no default collation is provided, the server's locale is used instead.
If the server's locale uses case-sensitive sorting, like the `C` locale for example, PostgreSQL will sort values in a case-sensitive manner.

Once the database is created, the only way to change it is to re-create a new database using another collation, or to set the collation on each column using [ALTER TABLE](https://www.postgresql.org/docs/current/sql-altertable.html).

## Solution

Add to the Faros requirements :
- [ ] the database must be created using the `fr_FR` collation (for example)
AND/OR
- [ ] the server's locale must be set to `fr_FR.UTF-8` (for example)

**Comment by lucasmirloup** [comment]
Cc @franck-lephare @jeremytirel
@thislg @pierreboissinot @caillaudv

**Comment by pierreboissinot** [comment]
@lucasmirloup let's add a server requirement **AND** db requirement.

We should add these requirements to each checklist.

**Comment by thislg** [comment]
I think fr_FR.UTF-8 is fine, but en_US.UTF-8 is also acceptable.

**Comment by pierreboissinot** [comment]
@thislg @lucasmirloup , @MorganVERNIERS assigned.

**Comment by pierreboissinot** [comment]
@MorganVERNIERS 3 checks:

- [ ] check locale intl PHP Config
- [ ] check locale postgres server (via s=query SQL PDO)
- [ ] check locale server

**note**: the database server may be on a different server thant php-fpm
