### ISSUE TITLE
fix(requirements): update network IPs/adresses

### ISSUE THREAD

**Issue by lucasmirloup** [le-phare/le-phare.github.io#140]
https://github.com/le-phare/le-phare.github.io/blob/4b7f1bc2423cdb70e7e30857fec6da314c1918b9/docs/static/configuration/network.md?plain=1#L9

## SSH sortant

- [ ] ~~Remove github.com IPs (prefer using deployer)~~
- [ ] Remove bitbucket.org
- [ ] Remove gitlab.com
- [ ] Remove gitlab.lephare.io

## HTTP/HTTPS output

- [ ] Remove bitbucket.org
- [ ] Remove gitlab.com

**Comment by pierreboissinot** [comment]
>Ok except for github.com which is our default source code server.

And gitlab.com
