### ISSUE TITLE
Script de vérification des prérequis : faux négatifs sur exécutables

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/le-phare.github.io#145]
relevé par @Temdi 

is_executable renverra faux pour les binaires testés via le user apache www-data.

Il faut les exclure du report et peut être ajouter une version cli ?

**Comment by MorganVERNIERS** [comment]
J'ai instancié un serveur apache, puis testé un fichier de test généré (le 2023.06). Je ne suis pas tombé sur de problème de faux négatif dans le test qui utilise is_executable. Je clotûre l'issue.
