### ISSUE TITLE
checkilist infra: why default pgsql version is 15 instead of 16 ?

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/le-phare.github.io#161]
https://github.com/le-phare/le-phare.github.io/blob/bffe644f891e658857b204e5a55a4bc15dc60a67/versions_data/2024.04.json#L28

@thislg une idée ?

**Comment by thislg** [comment]
On suit les versions proposées par Debian stable : actuellement c'est postgresql 15.

**Comment by pierreboissinot** [comment]
> On suit les versions proposées par Debian stable : actuellement c'est postgresql 15.

Je comprends mais ce n'est plus pertinent: aujourd'hui les bdd sont fournies as a service, indépendamment de ce que peut faire Debian.

**Comment by thislg** [comment]
Ça dépend toujours des cas mais je suis d'accord ça ne coûte rien de demander PostgreSQL 16 par défaut dans les prérequis.

**Comment by pierreboissinot** [comment]
@thislg je fais une pr pour update ça
