### ISSUE TITLE
fix path to lephare ssh public keys

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/le-phare.github.io#162]
https://lephare.slack.com/archives/C015VCJUK4G/p1713781861412849?thread_ts=1713518807.159399&cid=C015VCJUK4G

Regression 404:
https://faros.lephare.com/lephare.keys

Broken markdown:
https://faros.lephare.com/docs/versions/2024.04.html

:warning: ce path doit être utilisé par le server-inventory

**Comment by thislg** [comment]
[lephare_revoked.keys](https://github.com/le-phare/le-phare.github.io/blob/master/lephare_revoked.keys) aussi

**Comment by pierreboissinot** [comment]
@thislg yes je corrige ça

**Comment by lucasmirloup** [comment]
Merci @pierreboissinot :+1:
