### ISSUE TITLE
Add Brotli to requirements

### ISSUE THREAD

**Issue by thislg** [le-phare/le-phare.github.io#171]
Test automatically that Brotli compression works using the requirements script:
- Put a `.svg` file on the server
- Query it (on Internet) from the requirements script
- Check that the response header `Content-Encoding` equals `br`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

**Comment by lucasmirloup** [comment]
Only add Apache Brotli compression configuration for now.
