### ISSUE TITLE
Add php opcache.preload option

### ISSUE THREAD

**Issue by thislg** [le-phare/le-phare.github.io#185]
Symfony >= 4.4 and PHP >= 7.4 support preloading which is a free performance boost. We should add it to default php configuration.

https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading

https://symfony.com/blog/php-preloading-and-symfony

**Comment by pierreboissinot** [comment]
@thislg ce n'est pas dans la doc que ce sera écrit mais en tant que dev il faut savoir que le "naive preloading" apporte peu de gains par rapport à du preloading specific, faisable via des tags Symfony.

https://stitcher.io/blog/php-preload-benchmarks

**Comment by pierreboissinot** [comment]
@thislg Etant en train de configurer des LAMP pour un client, voici l'erreur (logique) au démarrage de php-fpm:

![image](https://github.com/user-attachments/assets/28ef9718-5cba-4c63-b8a3-0c9b4df67f21)

Il faut donc aussi préciser à l'hébergeur de mettre un dummy file au mm endroit.

Via Ansible:

![image](https://github.com/user-attachments/assets/182cab11-b9bf-4602-ac3b-9043c6e80e05)

**Comment by thislg** [comment]
Effectivement au fur et à mesure que PHP améliore ses performances, le gain introduit par le preload se réduit. Mais comme dit par Fabien Potencier, même 10% sont bons à prendre. Il reste le problème du cache à résoudre, s'il faut redémarrer fpm ça introduit un downtime qui me paraît peu souhaitable.

**Comment by thislg** [comment]
Conclusion : on ne peut pas demander cette configuration par défaut car elle peut poser problème dans certains cas.
